export interface PartnerRecord {
  id: string;
  name: string;
  initials: string;
  avatarBg: string;
  role: string;
  email: string;
  phone: string;
  status: string;
  dateAdded: string;
  avatar?: string;
}

export const masterPartnersList: PartnerRecord[] = [
  {
    id: "P-001",
    name: "Carles Mendez",
    initials: "CM",
    avatarBg: "bg-[#06B6D4]",
    role: "Vendor Manager",
    email: "carlos@northhills.com",
    phone: "+1 654 656 5656",
    status: "Active",
    dateAdded: "Jun 14, 2024",
  },
  {
    id: "P-002",
    name: "Emma Larsson",
    initials: "EL",
    avatarBg: "bg-[#A855F7]",
    role: "Partner Relations",
    email: "emma.l@valleyregion.com",
    phone: "+1 654 882 1920",
    status: "Active",
    dateAdded: "May 22, 2024",
  },
  {
    id: "P-003",
    name: "David Kwame",
    initials: "DK",
    avatarBg: "bg-[#EF4444]",
    role: "Supply Chain Director",
    email: "david.k@grainmasters.com",
    phone: "+1 654 991 2234",
    status: "Suspended",
    dateAdded: "Apr 04, 2024",
  },
  {
    id: "P-004",
    name: "Priya Nair",
    initials: "PN",
    avatarBg: "bg-[#3B82F6]",
    role: "Operations Lead",
    email: "priya@citygrocers.com",
    phone: "+1 654 331 8890",
    status: "Active",
    dateAdded: "Mar 18, 2024",
  },
  {
    id: "P-005",
    name: "James Okafor",
    initials: "JO",
    avatarBg: "bg-[#10B981]",
    role: "Procurement Head",
    email: "james@freshfarms.com",
    phone: "+1 654 442 1198",
    status: "Active",
    dateAdded: "Feb 08, 2024",
  },
  {
    id: "P-006",
    name: "Sophia Al-Mansoor",
    initials: "SA",
    avatarBg: "bg-[#F59E0B]",
    role: "Vendor Manager",
    email: "sophia@sunshinesuper.com",
    phone: "+1 654 771 9090",
    status: "Pending",
    dateAdded: "Jan 25, 2024",
  },
  {
    id: "P-007",
    name: "Lukas Bauer",
    initials: "LB",
    avatarBg: "bg-[#6366F1]",
    role: "Logistics Partner",
    email: "lukas.b@apexwholesale.com",
    phone: "+1 654 229 0011",
    status: "Active",
    dateAdded: "Jan 10, 2024",
  },
  {
    id: "P-008",
    name: "Amina Yusuf",
    initials: "AY",
    avatarBg: "bg-[#EC4899]",
    role: "Partner Relations",
    email: "amina@cornerstone.com",
    phone: "+1 654 883 4455",
    status: "Inactive",
    dateAdded: "Dec 19, 2023",
  },
  {
    id: "P-009",
    name: "Chen Wei",
    initials: "CW",
    avatarBg: "bg-[#14B8A6]",
    role: "Supply Chain Director",
    email: "chen.w@oceanic.com",
    phone: "+1 654 112 3344",
    status: "Active",
    dateAdded: "Nov 30, 2023",
  },
  {
    id: "P-010",
    name: "Isabella Rossi",
    initials: "IR",
    avatarBg: "bg-[#8B5CF6]",
    role: "Operations Lead",
    email: "isabella@urbanharvest.com",
    phone: "+1 654 554 6677",
    status: "Active",
    dateAdded: "Nov 12, 2023",
  },
  {
    id: "P-011",
    name: "Viktor Ivanov",
    initials: "VI",
    avatarBg: "bg-[#F97316]",
    role: "Vendor Manager",
    email: "viktor@goldenwheat.com",
    phone: "+1 654 332 1199",
    status: "Suspended",
    dateAdded: "Oct 28, 2023",
  },
  {
    id: "P-012",
    name: "Hannah Schmidt",
    initials: "HS",
    avatarBg: "bg-[#06B6D4]",
    role: "Procurement Head",
    email: "hannah@dailyneeds.com",
    phone: "+1 654 998 7766",
    status: "Active",
    dateAdded: "Oct 15, 2023",
  },
  {
    id: "P-013",
    name: "Tareq Hasan",
    initials: "TH",
    avatarBg: "bg-[#10B981]",
    role: "Partner Relations",
    email: "tareq.h@biofresh.com",
    phone: "+1 654 667 8899",
    status: "Pending",
    dateAdded: "Sep 22, 2023",
  },
  {
    id: "P-014",
    name: "Chloe Bennett",
    initials: "CB",
    avatarBg: "bg-[#A855F7]",
    role: "Operations Lead",
    email: "chloe@redappleretail.com",
    phone: "+1 654 445 5566",
    status: "Active",
    dateAdded: "Sep 05, 2023",
  },
  {
    id: "P-015",
    name: "Diego Fernandez",
    initials: "DF",
    avatarBg: "bg-[#3B82F6]",
    role: "Logistics Partner",
    email: "diego@evergreendairy.com",
    phone: "+1 654 119 8877",
    status: "Active",
    dateAdded: "Aug 18, 2023",
  },
  {
    id: "P-016",
    name: "Fatima Zahra",
    initials: "FZ",
    avatarBg: "bg-[#EC4899]",
    role: "Vendor Manager",
    email: "fatima@familychoice.com",
    phone: "+1 654 776 5544",
    status: "Inactive",
    dateAdded: "Aug 02, 2023",
  },
  {
    id: "P-017",
    name: "Gabriel Santos",
    initials: "GS",
    avatarBg: "bg-[#EF4444]",
    role: "Supply Chain Director",
    email: "gabriel@primemeat.com",
    phone: "+1 654 887 9900",
    status: "Active",
    dateAdded: "Jul 20, 2023",
  },
  {
    id: "P-018",
    name: "Kavita Rao",
    initials: "KR",
    avatarBg: "bg-[#F59E0B]",
    role: "Procurement Head",
    email: "kavita@expressmart.com",
    phone: "+1 654 223 3344",
    status: "Active",
    dateAdded: "Jul 04, 2023",
  },
  {
    id: "P-019",
    name: "Liam O'Connor",
    initials: "LO",
    avatarBg: "bg-[#6366F1]",
    role: "Partner Relations",
    email: "liam@orchardfresh.com",
    phone: "+1 654 556 6677",
    status: "Suspended",
    dateAdded: "Jun 18, 2023",
  },
  {
    id: "P-020",
    name: "Nadia Petrov",
    initials: "NP",
    avatarBg: "bg-[#14B8A6]",
    role: "Operations Lead",
    email: "nadia@bluesky.com",
    phone: "+1 654 990 1122",
    status: "Pending",
    dateAdded: "Jun 01, 2023",
  },
  {
    id: "P-021",
    name: "Oscar Vance",
    initials: "OV",
    avatarBg: "bg-[#8B5CF6]",
    role: "Vendor Manager",
    email: "oscar@summitgrain.com",
    phone: "+1 654 443 3322",
    status: "Active",
    dateAdded: "May 15, 2023",
  },
  {
    id: "P-022",
    name: "Penelope Cruz",
    initials: "PC",
    avatarBg: "bg-[#F97316]",
    role: "Logistics Partner",
    email: "penelope@greenleaf.com",
    phone: "+1 654 665 4433",
    status: "Active",
    dateAdded: "May 02, 2023",
  },
  {
    id: "P-023",
    name: "Quentin Blake",
    initials: "QB",
    avatarBg: "bg-[#06B6D4]",
    role: "Supply Chain Director",
    email: "quentin@puresprings.com",
    phone: "+1 654 889 0011",
    status: "Active",
    dateAdded: "Apr 19, 2023",
  },
  {
    id: "P-024",
    name: "Rashid Ali",
    initials: "RA",
    avatarBg: "bg-[#10B981]",
    role: "Procurement Head",
    email: "rashid@neighborhood.com",
    phone: "+1 654 112 2233",
    status: "Inactive",
    dateAdded: "Apr 05, 2023",
  },
  {
    id: "P-025",
    name: "Samantha Reed",
    initials: "SR",
    avatarBg: "bg-[#3B82F6]",
    role: "Partner Relations",
    email: "samantha@valleyspice.com",
    phone: "+1 654 778 9900",
    status: "Active",
    dateAdded: "Mar 22, 2023",
  },
];
