export interface PaymentTransactionRecord {
  id: string;
  customer: string;
  initials: string;
  avatarBg: string;
  amount: string;
  rawAmount: number;
  method: "Mobile Money" | "Bank Transfer" | "Card" | "Cash";
  status: "Completed" | "Pending" | "Failed";
  date: string;
}

export interface PayoutRecord {
  id: string;
  recipient: string;
  recipientType: "Rider" | "Partner";
  initials: string;
  avatarBg: string;
  amount: string;
  rawAmount: number;
  method: "Mobile Money" | "Bank Transfer";
  status: "Completed" | "Processing" | "Failed";
  date: string;
}

export const masterPaymentTransactions: PaymentTransactionRecord[] = [
  {
    id: "TXN-001284",
    customer: "Metro Mart",
    initials: "MM",
    avatarBg: "bg-[#06B6D4]",
    amount: "12 500 XOF",
    rawAmount: 12500,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 28, 2025",
  },
  {
    id: "TXN-001283",
    customer: "Fresh Farms LLC",
    initials: "FF",
    avatarBg: "bg-[#10B981]",
    amount: "8 750 XOF",
    rawAmount: 8750,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 27, 2025",
  },
  {
    id: "TXN-001282",
    customer: "City Grocers",
    initials: "CG",
    avatarBg: "bg-[#3B82F6]",
    amount: "5 200 XOF",
    rawAmount: 5200,
    method: "Mobile Money",
    status: "Pending",
    date: "Jun 27, 2025",
  },
  {
    id: "TXN-001281",
    customer: "Grain Masters",
    initials: "GM",
    avatarBg: "bg-[#EF4444]",
    amount: "19 800 XOF",
    rawAmount: 19800,
    method: "Card",
    status: "Failed",
    date: "Jun 26, 2025",
  },
  {
    id: "TXN-001280",
    customer: "Valley Region Co.",
    initials: "VR",
    avatarBg: "bg-[#A855F7]",
    amount: "6 300 XOF",
    rawAmount: 6300,
    method: "Cash",
    status: "Completed",
    date: "Jun 26, 2025",
  },
  {
    id: "TXN-001279",
    customer: "North Hills Supply",
    initials: "NH",
    avatarBg: "bg-[#06B6D4]",
    amount: "14 200 XOF",
    rawAmount: 14200,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 25, 2025",
  },
  {
    id: "TXN-001278",
    customer: "Apex Retailers",
    initials: "AR",
    avatarBg: "bg-[#F59E0B]",
    amount: "22 100 XOF",
    rawAmount: 22100,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 25, 2025",
  },
  {
    id: "TXN-001277",
    customer: "Alex Thompson",
    initials: "AT",
    avatarBg: "bg-[#10B981]",
    amount: "4 500 XOF",
    rawAmount: 4500,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 24, 2025",
  },
  {
    id: "TXN-001276",
    customer: "Sarah Jenkins",
    initials: "SJ",
    avatarBg: "bg-[#EC4899]",
    amount: "9 000 XOF",
    rawAmount: 9000,
    method: "Card",
    status: "Pending",
    date: "Jun 24, 2025",
  },
  {
    id: "TXN-001275",
    customer: "Marcus Wei",
    initials: "MW",
    avatarBg: "bg-[#3B82F6]",
    amount: "6 800 XOF",
    rawAmount: 6800,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 23, 2025",
  },
  {
    id: "TXN-001274",
    customer: "Elena Rodriguez",
    initials: "ER",
    avatarBg: "bg-[#8B5CF6]",
    amount: "8 200 XOF",
    rawAmount: 8200,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 23, 2025",
  },
  {
    id: "TXN-001273",
    customer: "Jamal Hossain",
    initials: "JH",
    avatarBg: "bg-[#F59E0B]",
    amount: "11 400 XOF",
    rawAmount: 11400,
    method: "Cash",
    status: "Failed",
    date: "Jun 22, 2025",
  },
  {
    id: "TXN-001272",
    customer: "Nusrat Jahan",
    initials: "NJ",
    avatarBg: "bg-[#10B981]",
    amount: "5 800 XOF",
    rawAmount: 5800,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 22, 2025",
  },
  {
    id: "TXN-001271",
    customer: "Tariqul Islam",
    initials: "TI",
    avatarBg: "bg-[#06B6D4]",
    amount: "7 500 XOF",
    rawAmount: 7500,
    method: "Card",
    status: "Completed",
    date: "Jun 21, 2025",
  },
  {
    id: "TXN-001270",
    customer: "Ayesha Siddiqua",
    initials: "AS",
    avatarBg: "bg-[#EC4899]",
    amount: "3 800 XOF",
    rawAmount: 3800,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 21, 2025",
  },
];

export const masterPayoutsList: PayoutRecord[] = [
  {
    id: "PO-90210",
    recipient: "Sumon Mia",
    recipientType: "Rider",
    initials: "SM",
    avatarBg: "bg-[#10B981]",
    amount: "45 000 XOF",
    rawAmount: 45000,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 28, 2025",
  },
  {
    id: "PO-90209",
    recipient: "Carles Mendez",
    recipientType: "Partner",
    initials: "CM",
    avatarBg: "bg-[#3B82F6]",
    amount: "120 000 XOF",
    rawAmount: 120000,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 28, 2025",
  },
  {
    id: "PO-90208",
    recipient: "Rafiqul Islam",
    recipientType: "Rider",
    initials: "RI",
    avatarBg: "bg-[#F59E0B]",
    amount: "38 500 XOF",
    rawAmount: 38500,
    method: "Mobile Money",
    status: "Processing",
    date: "Jun 27, 2025",
  },
  {
    id: "PO-90207",
    recipient: "Jahangir Alam",
    recipientType: "Rider",
    initials: "JA",
    avatarBg: "bg-[#8B5CF6]",
    amount: "52 000 XOF",
    rawAmount: 52000,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 27, 2025",
  },
  {
    id: "PO-90206",
    recipient: "Emma Larsson",
    recipientType: "Partner",
    initials: "EL",
    avatarBg: "bg-[#EC4899]",
    amount: "95 000 XOF",
    rawAmount: 95000,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 26, 2025",
  },
  {
    id: "PO-90205",
    recipient: "Tanvir Ahmed",
    recipientType: "Rider",
    initials: "TA",
    avatarBg: "bg-[#06B6D4]",
    amount: "28 000 XOF",
    rawAmount: 28000,
    method: "Mobile Money",
    status: "Failed",
    date: "Jun 26, 2025",
  },
  {
    id: "PO-90204",
    recipient: "David Kwame",
    recipientType: "Partner",
    initials: "DK",
    avatarBg: "bg-[#10B981]",
    amount: "150 000 XOF",
    rawAmount: 150000,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 25, 2025",
  },
  {
    id: "PO-90203",
    recipient: "Jahidul Islam",
    recipientType: "Rider",
    initials: "JI",
    avatarBg: "bg-[#3B82F6]",
    amount: "41 200 XOF",
    rawAmount: 41200,
    method: "Mobile Money",
    status: "Processing",
    date: "Jun 25, 2025",
  },
  {
    id: "PO-90202",
    recipient: "Priya Nair",
    recipientType: "Partner",
    initials: "PN",
    avatarBg: "bg-[#F59E0B]",
    amount: "88 000 XOF",
    rawAmount: 88000,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 24, 2025",
  },
  {
    id: "PO-90201",
    recipient: "Kazi Mamun",
    recipientType: "Rider",
    initials: "KM",
    avatarBg: "bg-[#8B5CF6]",
    amount: "34 000 XOF",
    rawAmount: 34000,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 24, 2025",
  },
  {
    id: "PO-90200",
    recipient: "James Okafor",
    recipientType: "Partner",
    initials: "JO",
    avatarBg: "bg-[#EC4899]",
    amount: "110 000 XOF",
    rawAmount: 110000,
    method: "Bank Transfer",
    status: "Completed",
    date: "Jun 23, 2025",
  },
  {
    id: "PO-90199",
    recipient: "Mahbubur Rahman",
    recipientType: "Rider",
    initials: "MR",
    avatarBg: "bg-[#06B6D4]",
    amount: "49 500 XOF",
    rawAmount: 49500,
    method: "Mobile Money",
    status: "Completed",
    date: "Jun 23, 2025",
  },
];
